[package]
name = "common"
version = "0.1.0"
edition = "2024"

[features]
axum = ["dep:axum"]

[dependencies]
eyre = { version = "0.6.12" }
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }

axum = { version = "0.8.1", features = ["macros"], optional = true }
